studentdb/config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :students
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

studentdb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

studentdb/app/models/project.rb
class Project < ApplicationRecord
    has_many :students
    has_many :project_evaluations
  
    validates :name, presence: true
    validates :url, presence: true, format: { with: URI::regexp(%w(http https))}
  end
  

studentdb/app/models/project_evaluation.rb
class ProjectEvaluation < ApplicationRecord
  belongs_to :project
  belongs_to :student
end

studentdb/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :project
  has_many :project_evaluations, dependent: :destroy

  validates :studentid, presence: true, uniqueness: { scope: :project_id }
  validates :name, presence: true
end

studentdb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

studentdb/app/controllers/projects_controller.rb
#Controller for Project Entities
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
    respond_to do |format|
    format.html
    format.json { render json: @projects }
    format.xml { render xml: @projects }
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    if @project.project_evaluations.exists?
      # Handle the case where project_evaluations exist
      # For example, set a flash message and redirect
      flash[:alert] = "Cannot delete project with existing evaluations."
      redirect_to projects_url
    else
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :url)
    end
end

studentdb/app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :set_project
  
    def create
      @student = @project.students.new(student_params)
      if @student.save
        redirect_to @project, notice: 'Student was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end    
  
    private
  
    def set_project
      @project = Project.find(params[:project_id])
    end
  
    def student_params
      params.require(:student).permit(:studentid, :name)
    end
  end
  

studentdb/app/helpers/application_helper.rb
module ApplicationHelper
end

studentdb/app/helpers/projects_helper.rb
module ProjectsHelper
end

studentdb/app/helpers/students_helper.rb
module StudentsHelper
end

studentdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

studentdb/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

studentdb/app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= project.url %>
  </p>

</div>

studentdb/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

studentdb/app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

studentdb/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

studentdb/app/views/projects/show.html.erb
<h2>Students</h2>
<table>
<thead>
<tr>
<th>Student ID </th>
<th>Name</th>
</tr>
</thead>
<tbody>
<% @project.students.each do |student| %>
<tr>
<td><%= student.studentid %></td>
<td><%= student.name %></td>
</tr>
<% end %>
</tbody>
</table>
<br/>
<h2>Add a student:</h2>
<%= form_for([@project, @project.students.build]) do |f| %>
<div class="field">
<%= f.label :studentid %><br />
<%= f.text_field :studentid %>
</div>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>
<br />

studentdb/app/views/students/_form.html.erb
<%= form_with(model: [@project, student]) do |form| %>
    <% if student.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
  
        <ul>
          <% student.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :studentid, style: "display: block" %>
      <%= form.text_field :studentid %>
    </div>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

studentdb/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", [@project, @student] %> |
  <%= link_to "Back to project", project_path(@project) %>
</div>

studentdb/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to project", project_path(@project) %>
</div>